### PR TITLE
CI: test against all supported Python versions

### PR DESCRIPTION
**Pull request by Guts**
Hello,

First of all, thanks for your great plugin. I'm using it on a big docs base and it works like a charm.

I'm the maintainer of the RSS plugin and using minify-plugin for the plugin documentation. So your plugin is not a critical dependency of my plugin but [I've been warned by dependabot](https://github.com/Guts/mkdocs-rss-plugin/pull/153) that upgrading your plugin to 0.6.* breaks my test and build.

I've checked and your plugin is supporting Python 3.7.

So in this PR, I propose to test the plugin against every Python supported versions (from [setup.py](https://github.com/byrnereese/mkdocs-minify-plugin/blob/master/setup.py#L27-L30))

### CODE REVIEW

**Comment by Guts** [comment]
Sorry @byrnereese, I forgot the main part of the workflow :sweat_smile:

**Comment by wilhelmer** [comment]
Thanks for contributing! 

The test fails because `test_basic.py` uses `dirs_exist_ok`, which was added in [Python 3.8](https://docs.python.org/3/whatsnew/3.8.html#shutil).

Can we just drop Python 3.8 support? I don't know how common 3.7 still is.

**Comment by wilhelmer** [comment]
Sorry, yes, I meant Python 3.7. But yes, if that's the only problem, we can fix that. I've already updated master with https://github.com/byrnereese/mkdocs-minify-plugin/commit/dd5645dba49b315fd142226b6d6dd61869598b75.

Now how can we rerun the test with the latest changes in master 🤔 If I click Details and Re-run jobs, it uses the old version of `test_basic.py` ...

**Comment by Guts** [comment]
> Now how can we rerun the test with the latest changes in master thinking If I click Details and Re-run jobs, it uses the old version of test_basic.py ...

Of course, I'm on my fork's branch. I've merge your master into my branch.

**Comment by wilhelmer** [comment]
Looks good then! Thanks!

**Comment by Guts** [comment]
You're welcome!

it does not solve my issue but well...

**Comment by wilhelmer** [comment]
Uh okay, let me know if there's anything I can do 🚁

**Pull request merged**
