### PR TITLE
resolve globs using pathlib.glob()

### LINKED ISSUE #35: Add support for glob syntax in `{css,js}_files` lists
I'd like to be able to list files to minify using glob syntax, which doesn't seem to be supported yet. For instance:

```yaml
plugins:
  - minify:
      css_files:
        - assets/css/**/*.css
```

I have several CSS files, many contain page-specific styles, so the list grows with more pages. Instead of maintaining a hardcoded list of files, I'd prefer using glob syntax.

The same applies to JS files, of course.

WDYT?

### PR DESCRIPTION
**Pull request by AdrianDsg**
fix #35 

I just managed to integrate support for globs as mentioned in #35.

There might be more efficient ways to integrate this feature. Please feel free to share your feeback below.

### CODE REVIEW

**Comment by byrnereese** [comment]
@AdrianDsg Thank you for the contribution. Do me one small favor - add something in the README.md about support for globs!

**Comment by byrnereese** [comment]
It also appears the unit tests are failing. I am not sure if this change caused this error, but could you take a look? I think we just need to update the HASH value in the assertion:

Update:
544b92316ee6219418120cfc0347f6f1b996f93833287777345da06a38f5f05e374d87a1a35e6bee96508169262d8f97
Change to:
468e45e1d823325ceebfd1c3eaa6e390c9629b43eaefcbdf5ff5d3c77cb358e10737d19d44ab0ad17f66a9935800c135


Update:
c102275d47fb49aeda0c2e35c35daf5da1ef5ce96f5360cf329578dc65e70b53249b20017b77bcc2516f672917d75762
Change to:
b164f41214bc362faf6a43c57be6c783a276ae188450b9f91ba27d4ffd581426e7e7902c9ce1dc93279f4b0badb92ec1

**Comment by AdrianDsg** [comment]
> It also appears the unit tests are failing. I am not sure if this change caused this error, but could you take a look? I think we just need to update the HASH value in the assertion [...]

@byrnereese you were mostly right about the reason for the failing tests. The file hashes needed to be replaced but I also had to fix a bug that I previously introduced when using pathlib to resolve globs.

**Comment by byrnereese** [comment]
Released as 0.8.0

**Pull request merged**
